apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iofogs.k8s.iofog.org
spec:
  group: k8s.iofog.org
  names:
    kind: IOFog
    listKind: IOFogList
    plural: iofogs
    singular: iofog
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
      labelSelectorPath: .status.labelSelector