apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.iofog.org
spec:
  group: iofog.org
  names:
    kind: Application
    listKind: ApplicationList
    plural: apps
    singular: app
  scope: Namespaced
  subresources:
    status: {}
  version: v2
  versions:
  - name: v2
    served: true
    storage: true
